# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    scan(scheme: "BYTBibleDiary")
  end
  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end
  lane :beta do
    increment_version_number({
      version_number: get_version_number(xcodeproj: "BYTBibleDiary.xcodeproj", target: "BYTBibleDiary"),
    })
    increment_build_number({
      build_number: latest_testflight_build_number(username: "u9951062@icloud.com", app_identifier: "com.banner.takeitover") + 1,
    })
    match(
      app_identifier: "com.banner.takeitover",
      type: "appstore",
      git_url: "https://gitlab.com/Youngdi/takeover",
      readonly: true,
    )
    gym(
      scheme: "BYTBibleDiary",
      silent: true,
      clean: true
    )
    crashlytics(
      api_token: "ef189b81854fb9fdefca6ba4715bf2e9a1e80e11",
      build_secret: "ab34646c123227eb4fb4bef1652ae7ff9493febf8b396ddf91c2f68c6163ae8d",
      ipa_path: "./BYTBibleDiary.ipa",
      crashlytics_path: './Pods/Crashlytics/iOS/Crashlytics.framework',
      notes: 'Latest Beta build'
    )
    pilot(
      username: "u9951062@icloud.com",
      app_identifier: "com.banner.takeitover",
      skip_waiting_for_build_processing: true
    )
  end
  lane :release do 
    increment_version_number({
      version_number: get_version_number(xcodeproj: "BYTBibleDiary.xcodeproj", target: "BYTBibleDiary"),
    })
    increment_build_number({
      build_number: latest_testflight_build_number(username: "u9951062@icloud.com", app_identifier: "com.banner.takeitover") + 1,
    })
    match(
      app_identifier: "com.banner.takeitover",
      type: "appstore",
      git_url: "https://gitlab.com/Youngdi/takeover",
      readonly: true,
    )
    gym(
      scheme: "BYTBibleDiary",
      silent: true,
      clean: true
    )
    deliver(
      submit_for_review: true,
      force: true,
      metadata_path: "./metadata"
    )
  end
end
