# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics(
      api_token: "ef189b81854fb9fdefca6ba4715bf2e9a1e80e11",
      build_secret: "ab34646c123227eb4fb4bef1652ae7ff9493febf8b396ddf91c2f68c6163ae8d",
      apk_path: "./app/build/outputs/apk/release/app-release.apk"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    gradle(task: "clean assembleRelease")
    supply
  end
end
